apiVersion: v1
kind: Service
metadata:
  name: simple-mirror-k8s
spec:
  selector:
    app.kubernetes.io/name: simple-mirror-k8s
  type: NodePort
  ports:
    - name: simple-mirror-k8s-port
      protocol: TCP
      port: 7777
      targetPort: 7777
      nodePort: 31520
